FROM python:3.10.13

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt --no-cache-dir

COPY unet.h5 .
COPY entrypoint.py .
COPY inference.py .

ENTRYPOINT ["python", "entrypoint.py"]